---
# tasks file for role_nutanix_pe_update_cluster
- name: Setup connection to Nutanix API
  ansible.builtin.include_role:
    name: grdavies.role_nutanix_prism_api
  vars:
    role_nutanix_prism_api_host: "{{ role_nutanix_pe_update_cluster_host }}"
    role_nutanix_prism_api_host_username: "{{ role_nutanix_pe_update_cluster_host_username }}"
    role_nutanix_prism_api_host_password: "{{ role_nutanix_pe_update_cluster_host_password }}"
    role_nutanix_prism_api_host_port: "{{ role_nutanix_pe_update_cluster_host_port }}"
    role_nutanix_prism_api_host_validate_certs: "{{ role_nutanix_pe_update_cluster_host_validate_certs }}"
    role_nutanix_prism_api_debug: "{{ role_nutanix_pe_update_cluster_debug }}"

- name: "Task can only be run against Prism Element"
  ansible.builtin.fail:
    msg: "'role_nutanix_pe_update_cluster_host' needs to be set to the VIP of a Nutanix cluster. Please check the variable and try again."
  when:
    - role_nutanix_prism_api_endpoint_type != 'pe'

- name: Get Nutanix v2 cluster info
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/cluster"
    method: GET
    validate_certs: "{{ role_nutanix_pe_update_cluster_host_validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
  register: role_nutanix_pe_update_existing_v2_config

- name: Debug role_nutanix_pe_update_existing_v2_config.json
  ansible.builtin.debug:
    var: role_nutanix_pe_update_existing_v2_config.json
  when:
    - role_nutanix_pe_update_cluster_debug

- name: Extract cluster UUID
  ansible.builtin.set_fact:
    role_nutanix_pe_update_existing_cluster_uuid: "{{ role_nutanix_pe_update_existing_v2_config.json.cluster_uuid }}"

- name: Debug role_nutanix_pe_update_existing_cluster_uuid
  ansible.builtin.debug:
    var: role_nutanix_pe_update_existing_cluster_uuid
  when:
    - role_nutanix_pe_update_cluster_debug

- name: Get Nutanix cluster spec
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/nutanix/v3/clusters/{{ role_nutanix_pe_update_existing_cluster_uuid }}"
    method: GET
    validate_certs: "{{ role_nutanix_pe_update_cluster_host_validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
  register: role_nutanix_pe_update_existing_v3_cluster_spec

- name: Debug role_nutanix_pe_update_existing_v3_cluster_spec.json
  ansible.builtin.debug:
    var: role_nutanix_pe_update_existing_v3_cluster_spec.json
  when:
    - role_nutanix_pe_update_cluster_debug

- name: Create Target Cluster Spec
  ansible.builtin.set_fact:
    role_nutanix_pe_update_new_v3_cluster_spec: "{{ role_nutanix_pe_update_existing_v3_cluster_spec.json.spec }}"

# cluster_name
- name: Update Target Cluster Spec with role_nutanix_pe_update_cluster_name
  ansible.utils.update_fact:
    updates:
      - path: role_nutanix_pe_update_new_v3_cluster_spec.name
        value: "{{ role_nutanix_pe_update_cluster_name }}"
  register: role_nutanix_pe_update_changed_v3_cluster_spec_cluster_name
  when:
    - role_nutanix_pe_update_cluster_name is defined

- name: Update role_nutanix_pe_update_new_v3_cluster_spec with changes
  ansible.builtin.set_fact:
    role_nutanix_pe_update_new_v3_cluster_spec: "{{ role_nutanix_pe_update_changed_v3_cluster_spec_cluster_name.role_nutanix_pe_update_new_v3_cluster_spec }}"
  when:
    - role_nutanix_pe_update_changed_v3_cluster_spec_cluster_name.changed
    - not role_nutanix_pe_update_changed_v3_cluster_spec_cluster_name.failed

# role_nutanix_pe_update_cluster_virtual_ip
- name: Update Target Cluster Spec with role_nutanix_pe_update_cluster_virtual_ip
  ansible.utils.update_fact:
    updates:
      - path: role_nutanix_pe_update_new_v3_cluster_spec.resources.network.external_ip
        value: "{{ role_nutanix_pe_update_cluster_virtual_ip }}"
  register: role_nutanix_pe_update_changed_v3_cluster_spec_virtual_ip
  when:
    - role_nutanix_pe_update_cluster_virtual_ip is defined

- name: Update role_nutanix_pe_update_new_v3_cluster_spec with changes
  ansible.builtin.set_fact:
    role_nutanix_pe_update_new_v3_cluster_spec: "{{ role_nutanix_pe_update_changed_v3_cluster_spec_virtual_ip.role_nutanix_pe_update_new_v3_cluster_spec }}"
  when:
    - role_nutanix_pe_update_changed_v3_cluster_spec_virtual_ip.changed
    - not role_nutanix_pe_update_changed_v3_cluster_spec_virtual_ip.failed

# data_services_ip
- name: Update Target Cluster Spec with role_nutanix_pe_update_cluster_data_services_ip
  ansible.utils.update_fact:
    updates:
      - path: role_nutanix_pe_update_new_v3_cluster_spec.resources.network.external_data_services_ip
        value: "{{ role_nutanix_pe_update_cluster_data_services_ip }}"
  register: role_nutanix_pe_update_changed_v3_cluster_spec_data_services_ip
  when:
    - role_nutanix_pe_update_cluster_data_services_ip is defined

- name: Update role_nutanix_pe_update_new_v3_cluster_spec with changes
  ansible.builtin.set_fact:
    role_nutanix_pe_update_new_v3_cluster_spec: "{{ role_nutanix_pe_update_changed_v3_cluster_spec_data_services_ip.role_nutanix_pe_update_new_v3_cluster_spec }}"
  when:
    - role_nutanix_pe_update_changed_v3_cluster_spec_data_services_ip.changed
    - not role_nutanix_pe_update_changed_v3_cluster_spec_data_services_ip.failed

# rf_level
- name: Update Target Cluster Spec with role_nutanix_pe_update_cluster_rf_level
  ansible.utils.update_fact:
    updates:
      - path: role_nutanix_pe_update_new_v3_cluster_spec.resources.config.redundancy_factor
        value: "{{ role_nutanix_pe_update_cluster_rf_level }}"
  register: role_nutanix_pe_update_changed_v3_cluster_spec_rf_level
  when:
    - role_nutanix_pe_update_cluster_rf_level is defined
    - role_nutanix_pe_update_cluster_rf_level in [1, 2, 3]

- name: Update role_nutanix_pe_update_new_v3_cluster_spec with changes
  ansible.builtin.set_fact:
    role_nutanix_pe_update_new_v3_cluster_spec: "{{ role_nutanix_pe_update_changed_v3_cluster_spec_rf_level.role_nutanix_pe_update_new_v3_cluster_spec }}"
  when:
    - role_nutanix_pe_update_changed_v3_cluster_spec_rf_level.changed
    - not role_nutanix_pe_update_changed_v3_cluster_spec_rf_level.failed

- name: Debug role_nutanix_pe_update_new_v3_cluster_spec
  ansible.builtin.debug:
    var: role_nutanix_pe_update_new_v3_cluster_spec
  when:
    - role_nutanix_pe_update_cluster_debug

- name: Update Nutanix cluster settings
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/nutanix/v3/clusters/{{ role_nutanix_pe_update_existing_cluster_uuid }}"
    method: PUT
    validate_certs: "{{ role_nutanix_pe_update_cluster_host_validate_certs }}"
    body_format: json
    status_code: 202
    body:
      metadata: "{{ role_nutanix_pe_update_existing_v3_cluster_spec.json.metadata }}"
      spec: "{{ role_nutanix_pe_update_new_v3_cluster_spec }}"
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
  when:
    - ( role_nutanix_pe_update_changed_v3_cluster_spec_cluster_name.changed or
      role_nutanix_pe_update_changed_v3_cluster_spec_virtual_ip.changed or
      role_nutanix_pe_update_changed_v3_cluster_spec_data_services_ip.changed or
      role_nutanix_pe_update_changed_v3_cluster_spec_rf_level.changed )
    - not role_nutanix_pe_update_changed_v3_cluster_spec_cluster_name.failed | default(false)
    - not role_nutanix_pe_update_changed_v3_cluster_spec_virtual_ip.failed | default(false)
    - not role_nutanix_pe_update_changed_v3_cluster_spec_data_services_ip.failed | default(false)
    - not role_nutanix_pe_update_changed_v3_cluster_spec_rf_level.failed | default(false)
  register: nutanix_prism_cluster_new_spec_put

- name: Debug nutanix_prism_cluster_new_spec_put
  ansible.builtin.debug:
    var: nutanix_prism_cluster_new_spec_put
  when:
    - role_nutanix_pe_update_cluster_debug

- name: Wait for cluster update task to complete
  ansible.builtin.import_role:
    name: grdavies.role_nutanix_prism_monitor_task
  vars:
    role_nutanix_prism_monitor_task_host: "{{ role_nutanix_pe_update_cluster_host }}"
    role_nutanix_prism_monitor_task_host_username: "{{ role_nutanix_pe_update_cluster_host_username }}"
    role_nutanix_prism_monitor_task_host_password: "{{ role_nutanix_pe_update_cluster_host_password }}"
    role_nutanix_prism_monitor_task_host_port: "{{ role_nutanix_pe_update_cluster_host_port }}"
    role_nutanix_prism_monitor_task_host_validate_certs: "{{ role_nutanix_pe_update_cluster_host_validate_certs }}"
    role_nutanix_prism_monitor_task_debug: "{{ role_nutanix_pe_update_cluster_debug }}"
    role_nutanix_prism_monitor_task_uuid: "{{ nutanix_prism_cluster_new_spec_put.json.status.execution_context.task_uuid }}"
    role_nutanix_prism_monitor_task_retries: 30
    role_nutanix_prism_monitor_task_retry_delay: 5
  when:
    - ( role_nutanix_pe_update_changed_v3_cluster_spec_cluster_name.changed or
      role_nutanix_pe_update_changed_v3_cluster_spec_virtual_ip.changed or
      role_nutanix_pe_update_changed_v3_cluster_spec_data_services_ip.changed or
      role_nutanix_pe_update_changed_v3_cluster_spec_rf_level.changed )
    - not role_nutanix_pe_update_changed_v3_cluster_spec_cluster_name.failed | default(false)
    - not role_nutanix_pe_update_changed_v3_cluster_spec_virtual_ip.failed | default(false)
    - not role_nutanix_pe_update_changed_v3_cluster_spec_data_services_ip.failed | default(false)
    - not role_nutanix_pe_update_changed_v3_cluster_spec_rf_level.failed | default(false)
