---
# tasks file for nutanix_role_prism_cluster_update
- name: Setup connection to Nutanix API
  ansible.builtin.include_tasks: setup_api.yml

- name: "Task can only be run against Prism Element"
  ansible.builtin.fail:
    msg: "'nutanix_host' needs to be set to the VIP of a Nutanix cluster. Please check the variable and try again."
  when:
    - nutanix_endpoint_prism_type != 'pe'

- name: Get Nutanix v2 cluster info
  ansible.builtin.uri:
    url: "https://{{ nutanix_host }}:{{ nutanix_port }}/PrismGateway/services/rest/v2.0/cluster"
    method: GET
    validate_certs: "{{ validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ nutanix_api_auth }}"
    return_content: true
  register: nutanix_prism_cluster_current_config

- name: Debug nutanix_prism_cluster_current_config.json
  ansible.builtin.debug:
    var: nutanix_prism_cluster_current_config.json
  when:
    - nutanix_debug

- name: Extract cluster UUID
  ansible.builtin.set_fact:
    update_cluster_uuid: "{{ nutanix_prism_cluster_current_config.json.cluster_uuid }}"

- name: Debug update_cluster_uuid
  ansible.builtin.debug:
    var: update_cluster_uuid
  when:
    - nutanix_debug

- name: Get Nutanix cluster spec
  ansible.builtin.uri:
    url: "https://{{ nutanix_host }}:{{ nutanix_port }}/api/nutanix/v3/clusters/{{ update_cluster_uuid }}"
    method: GET
    validate_certs: "{{ validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ nutanix_api_auth }}"
    return_content: true
  register: nutanix_prism_cluster_current_spec

- name: Debug nutanix_prism_cluster_current_spec.json
  ansible.builtin.debug:
    var: nutanix_prism_cluster_current_spec.json
  when:
    - nutanix_debug

- name: Create Target Cluster Spec
  ansible.builtin.set_fact:
    nutanix_prism_cluster_new_spec: "{{ nutanix_prism_cluster_current_spec.json.spec }}"

# cluster_name
- name: Update Target Cluster Spec with update_cluster_name
  ansible.utils.update_fact:
    updates:
      - path: nutanix_prism_cluster_new_spec.name
        value: "{{ update_cluster_name }}"
  register: nutanix_prism_cluster_new_spec_update_cluster_name
  when:
    - update_cluster_name is defined

- name: Update nutanix_prism_cluster_new_spec with changes
  ansible.builtin.set_fact:
    nutanix_prism_cluster_new_spec: "{{ nutanix_prism_cluster_new_spec_update_cluster_name.nutanix_prism_cluster_new_spec }}"
  when:
    - nutanix_prism_cluster_new_spec_update_cluster_name.changed
    - not nutanix_prism_cluster_new_spec_update_cluster_name.failed

# update_cluster_virtual_ip
- name: Update Target Cluster Spec with update_cluster_virtual_ip
  ansible.utils.update_fact:
    updates:
      - path: nutanix_prism_cluster_new_spec.resources.network.external_ip
        value: "{{ update_cluster_virtual_ip }}"
  register: nutanix_prism_cluster_new_spec_update_cluster_virtual_ip
  when:
    - update_cluster_virtual_ip is defined

- name: Update nutanix_prism_cluster_new_spec with changes
  ansible.builtin.set_fact:
    nutanix_prism_cluster_new_spec: "{{ nutanix_prism_cluster_new_spec_update_cluster_virtual_ip.nutanix_prism_cluster_new_spec }}"
  when:
    - nutanix_prism_cluster_new_spec_update_cluster_virtual_ip.changed
    - not nutanix_prism_cluster_new_spec_update_cluster_virtual_ip.failed

# data_services_ip
- name: Update Target Cluster Spec with update_data_services_ip
  ansible.utils.update_fact:
    updates:
      - path: nutanix_prism_cluster_new_spec.resources.network.external_data_services_ip
        value: "{{ update_data_services_ip }}"
  register: nutanix_prism_cluster_new_spec_update_data_services_ip
  when:
    - update_data_services_ip is defined

- name: Update nutanix_prism_cluster_new_spec with changes
  ansible.builtin.set_fact:
    nutanix_prism_cluster_new_spec: "{{ nutanix_prism_cluster_new_spec_update_data_services_ip.nutanix_prism_cluster_new_spec }}"
  when:
    - nutanix_prism_cluster_new_spec_update_data_services_ip.changed
    - not nutanix_prism_cluster_new_spec_update_data_services_ip.failed

# rf_level
- name: Update Target Cluster Spec with update_rf_level
  ansible.utils.update_fact:
    updates:
      - path: nutanix_prism_cluster_new_spec.resources.config.redundancy_factor
        value: "{{ update_rf_level }}"
  register: nutanix_prism_cluster_new_spec_update_rf_level
  when:
    - update_rf_level is defined
    - update_rf_level in [1, 2, 3]

- name: Update nutanix_prism_cluster_new_spec with changes
  ansible.builtin.set_fact:
    nutanix_prism_cluster_new_spec: "{{ nutanix_prism_cluster_new_spec_update_rf_level.nutanix_prism_cluster_new_spec }}"
  when:
    - nutanix_prism_cluster_new_spec_update_rf_level.changed
    - not nutanix_prism_cluster_new_spec_update_rf_level.failed

- name: Debug nutanix_prism_cluster_new_spec
  ansible.builtin.debug:
    var: nutanix_prism_cluster_new_spec
  when:
    - nutanix_debug

- name: Update Nutanix cluster settings
  ansible.builtin.uri:
    url: "https://{{ nutanix_host }}:{{ nutanix_port }}/api/nutanix/v3/clusters/{{ update_cluster_uuid }}"
    method: PUT
    validate_certs: "{{ validate_certs }}"
    body_format: json
    status_code: 202
    body:
      metadata: "{{ nutanix_prism_cluster_current_spec.json.metadata }}"
      spec: "{{ nutanix_prism_cluster_new_spec }}"
    headers:
      Authorization: "{{ nutanix_api_auth }}"
    return_content: true
  when:
    - ( nutanix_prism_cluster_new_spec_update_cluster_name.changed or
      nutanix_prism_cluster_new_spec_update_cluster_virtual_ip.changed or
      nutanix_prism_cluster_new_spec_update_data_services_ip.changed or
      nutanix_prism_cluster_new_spec_update_rf_level.changed )
    - not nutanix_prism_cluster_new_spec_update_cluster_name.failed | default(false)
    - not nutanix_prism_cluster_new_spec_update_cluster_virtual_ip.failed | default(false)
    - not nutanix_prism_cluster_new_spec_update_data_services_ip.failed | default(false)
    - not nutanix_prism_cluster_new_spec_update_rf_level.failed | default(false)
  register: nutanix_prism_cluster_new_spec_put

- name: Debug nutanix_prism_cluster_new_spec_put
  ansible.builtin.debug:
    var: nutanix_prism_cluster_new_spec_put
  when:
    - nutanix_debug

- name: Wait for cluster update task to complete
  ansible.builtin.import_role:
    name: grdavies.role_nutanix_prism_monitor_task
  vars:
    nutanix_task_uuid: "{{ nutanix_prism_cluster_new_spec_put.json.status.execution_context.task_uuid }}"
    nutanix_task_retries: 30
    nutanix_task_retry_delay: 5
  when:
    - ( nutanix_prism_cluster_new_spec_update_cluster_name.changed or
      nutanix_prism_cluster_new_spec_update_cluster_virtual_ip.changed or
      nutanix_prism_cluster_new_spec_update_data_services_ip.changed or
      nutanix_prism_cluster_new_spec_update_rf_level.changed )
    - not nutanix_prism_cluster_new_spec_update_cluster_name.failed | default(false)
    - not nutanix_prism_cluster_new_spec_update_cluster_virtual_ip.failed | default(false)
    - not nutanix_prism_cluster_new_spec_update_data_services_ip.failed | default(false)
    - not nutanix_prism_cluster_new_spec_update_rf_level.failed | default(false)
